### ISSUE TITLE
[BUG][iOS] Crash: NSInternalInconsistencyException

### ISSUE THREAD

**Issue by eunjoo-choi** [microsoft/clarity-apps#118]
**Describe the Bug**
```
          Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x11a21c __exceptionPreprocess
1  libobjc.A.dylib                0x31abc objc_exception_throw
2  Foundation                     0x79e810 -[NSMutableDictionary(NSMutableDictionary) initWithContentsOfFile:]
3  UIKitCore                      0x2c5bbc _UIGraphicsBeginImageContextWithOptions
4  Clarity                        0x12738 (누락 UUID 9d04055be4f836648bd18beed73f951c)
5  Clarity                        0xd3d8 (누락 UUID 9d04055be4f836648bd18beed73f951c)
6  Clarity                        0x7cb4 (누락 UUID 9d04055be4f836648bd18beed73f951c)
7  Clarity                        0x6778 (누락 UUID 9d04055be4f836648bd18beed73f951c)
8  Foundation                     0x2c8c78 _startElementNs
9  libxml2.2.dylib                0xa4f0 xmlParseStartTag2
10 libxml2.2.dylib                0x138ac xmlParseTryOrFinish
11 libxml2.2.dylib                0x12a64 xmlParseChunk
12 Foundation                     0x2ed930 -[NSXMLParser parseData:]
13 Foundation                     0x2edac0 -[NSXMLParser parseData:]
14 Foundation                     0x2ed688 -[NSXMLParser parseFromStream]
15 Clarity                        0x120e8 (누락 UUID 9d04055be4f836648bd18beed73f951c)
16 Clarity                        0x5b14 (누락 UUID 9d04055be4f836648bd18beed73f951c)
17 Clarity                        0x55b0 (누락 UUID 9d04055be4f836648bd18beed73f951c)
18 Clarity                        0x11a324 (누락 UUID 9d04055be4f836648bd18beed73f951c)
19 Clarity                        0x1197a0 (누락 UUID 9d04055be4f836648bd18beed73f951c)
20 Clarity                        0x11937c (누락 UUID 9d04055be4f836648bd18beed73f951c)
21 Clarity                        0x117fdc (누락 UUID 9d04055be4f836648bd18beed73f951c)
22 libdispatch.dylib              0x1aac _dispatch_call_block_and_release
23 libdispatch.dylib              0x1b584 _dispatch_client_callout
24 libdispatch.dylib              0xa2d0 _dispatch_lane_serial_drain
25 libdispatch.dylib              0xadac _dispatch_lane_invoke
26 libdispatch.dylib              0x151dc _dispatch_root_queue_drain_deferred_wlh
27 libdispatch.dylib              0x14a60 _dispatch_workloop_worker_thread
28 libsystem_pthread.dylib        0xa0c _pthread_wqthread
29 libsystem_pthread.dylib        0xaac start_wqthread
        
```

**Screenshots**
![Image](https://github.com/user-attachments/assets/c9e2eca9-ba5b-4271-8577-08d123e9c68f)

**Project Info**
- Project ID (qv2205ahae)

**Platform/Framework Info**

- Device: iPhone 12 Pro
- OS: iOS 18.5.0
- Application Framework: Native SwiftUI-based
- Clarity Version: 3.0.7

**Additional Context**
The app is primarily implemented using SwiftUI, but UIKit components are also mixed in and used within the project. Since the project uses SwiftUI, we are using Clarity SDK version 3.0.x to ensure compatibility.

**Comment by amralaa-MSFT** [comment]
@eunjoo-choi, please attach the full crash log as an *.ips file.

**Comment by amralaa-MSFT** [comment]
@eunjoo-choi, thanks for providing the full crash log. Could you also let us know the following:

1. Are there any repro steps to trigger the crash in your app?
2. Does the current version on the App Store have Clarity integrated? If so, please provide the link to the app.

**Comment by eunjoo-choi** [comment]
We're really sorry, but we don't have specific reproduction steps for the crash at this time. The issue has not occurred on our test devices or in the development environment so far.

Clarity is integrated in the current version of the app on the App Store. However, the app is only available in the Korean App Store, so you might not be able to access it from your region.  [KR App Store Link](https://apps.apple.com/kr/app/%ED%8D%BC%EA%B7%B8%EC%83%B5/id6742388034)

If it helps, one potential area of suspicion is a part of the app where we implemented UICollectionView cells using SwiftUI in the version where the issue was reported. For image loading in that component, we are using the Kingfisher library.

**Comment by ibradwan** [comment]
@eunjoo-choi 
Do you, by any chance, load extra large images in your application?

**Comment by eunjoo-choi** [comment]
Our app does not have an image upload feature that allows users to upload large-sized images. Additionally, we don't load high-resolution or large-sized images when displaying content in the app.

**Comment by ibradwan** [comment]
@eunjoo-choi Thanks for getting back to us.

How often does this crash happen? Additionally, if it has happened more than once, can you share a handful of similar screenshots of those crashes?

![Image](https://github.com/user-attachments/assets/1ff7ae6b-09ca-44d9-93ee-0ba71b1dfd63)

**Comment by ibradwan** [comment]
Hey,

After investigating the issue, it might be caused by an issue that was addressed in 3.0.8, could u please upgrade and give it a shot?

**Comment by eunjoo-choi** [comment]
Thanks for the follow-up!

The same crash is still occurring even after the version upgrade.
Unfortunately, due to company policy, we’re unable to share the IPA externally.

That said, I’ll continue investigating on my end as well, and I’ll share any additional findings or crash reports that might help with the analysis.

![Image](https://github.com/user-attachments/assets/aeefe103-a205-4565-ae45-0b99cec829c5)

![Image](https://github.com/user-attachments/assets/a76dc235-1264-402a-a269-90eebf903dc4)

**Comment by ibradwan** [comment]
Thanks for sharing that. We'll release a patch very soon to address this issue.

**Comment by ibradwan** [comment]
@eunjoo-choi we've released 3.0.9 which should resolve this issue, please give it a shot and let us know.
