### ISSUE TITLE
[BUG][iOS] Bug Report

### ISSUE THREAD

**Issue by taocheng-njfu** [microsoft/clarity-apps#182]
it is crashed on iPhone SE,but not crash on iPhone 13pro max, this is the crash log:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
*** First throw call stack:
(0x18592c0c0 0x182dc5abc 0x1a9921d1c 0x1a9922dec 0x1a9922d1c 0x1a9922aa8 0x188126b28 0x188364aa4 0x18839ac38 0x241561300 0x2432fb340 0x242f96d38 0x10187d3ac 0x10187d074 0x10187cc7c 0x10187c6a0 0x10189051c 0x10188c184 0x101cf4584 0x101d0e064 0x101cfc91c 0x101cfd5a4 0x101d09894 0x101d08eb0 0x20fcb4a0c 0x20fcb4aac)
terminating due to uncaught exception of type NSException
Can't show file for stack frame : <DBGLLDBStackFrame: 0x3aa5804d0> - stackNumber:20 - name:specialized static ClickProcessor.CandidateTextNode.nodeText(_:). The file path does not exist on the file system: /Users/runner/work/1/s/Clarity/Clarity/Helpers/ClickProcessor.swift

**Comment by ibradwan** [comment]
@taocheng-njfu this issue has been resolved in a recent version. Please make sure to use the latest Clarity version.

**Comment by taocheng-njfu** [comment]
<img width="1393" height="689" alt="Image" src="https://github.com/user-attachments/assets/7d8e81c2-8c83-40b2-a4df-dfc0350e487f" /> I have update to 3.1.1 version, the crash is still there

**Comment by ibradwan** [comment]
@taocheng-njfu could you please share your project id and app link to clarity-apps-support@microsoft.com?
